name: Build_Windows_EXE_Production
on: [push] # Otomatis jalan setiap kali Anda 'git push'

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Libraries
        run: |
          python -m pip install --upgrade pip
          pip install feedparser pandas textblob openpyxl pyinstaller
          python -m textblob.download_corpora # Penting untuk fitur sentimen

      - name: Create EXE with PyInstaller
        # --noconsole agar tidak muncul jendela hitam, atau hapus jika ingin melihat log saat jalan
        run: pyinstaller --onefile --name "MonitorBeritaJabar_v1" monitoring.py

      - name: Upload Finished EXE
        uses: actions/upload-artifact@v3
        with:
          name: Aplikasi_Monitoring_Windows
          path: dist/MonitorBeritaJabar_v1.exe
